### PR TITLE
add support for postgresql_db 'target'; resolves #5

### LINKED ISSUE #5: add support for Ansible 2.4 postgresql_db 'target'
We should be able to use postgresql_db module's `target` parameter (from Ansible 2.4 onwards).

### PR DESCRIPTION
**Pull request by mkozjak**
Signed-off-by: Mario Kozjak <kozjakm1@gmail.com>

### CODE REVIEW

**Comment by mkozjak** [comment]
This one still needs a solution where the `state` param would be set to `restore` if the schema is provided!

**Comment by mkozjak** [comment]
Ok, looking good. Done!

**Comment by mkozjak** [comment]
@volodymyr-mykhailyk: Can you merge this, maybe?

**Comment by volodymyr-mykhailyk** [comment]
Thanks for help and sorry for delay with merge @mkozjak

**Pull request merged**
